apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carbone-ee.fullname" . }}
type: Opaque
stringData:
  license: {{ .Values.applicationConfiguration.license | quote }}
  publicKey: {{ .Values.applicationConfiguration.authenticationPublicKey | quote }}
  s3AccesKeyId: {{ .Values.persistentStorage.s3.accessKeyId | quote }}
  s3AccessKeySecret: {{ .Values.persistentStorage.s3.accessKeySecret | quote }}
  azureStorageKey: {{ .Values.persistentStorage.azureBlobStorage.storageKey | quote }}