apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "carbone-ee.fullname" .) }}
  labels:
    {{- include "carbone-ee.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "carbone-ee.selectorLabels" . | nindent 4 }}
  clusterIP: None
  ports:
    - port: {{ .Values.applicationConfiguration.port }}
      targetPort: http
      protocol: TCP
      name: http
